name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-latest
    steps:
      - uses: gabrielrufino/check-ci@main
      - uses: actions/checkout@v4
      - run: echo "Your delivery here"
